apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-
spec:
  serviceAccountName: zuzana-drozdova-zuzana-drozdova-service
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/zuzana-drozdova-express-sample
    - name: image-repo
      value: quay.io/zuzana_drozdova/express-sample-app
    - name: app-name
      value: zuzana-drozdova-express
  pipelineRef:
    name: express-sample-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce